name: Java with Nexus Repository

on:
  pull_request:
    types:
      - merged
    branches:
      - 'main'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: http://163c6cdd.ngrok.io
        username: admin
        password: ${{ secrets.password }}
        format: gradle  
        repository: gradle-releases
        coordinates: groupId=com.example artifactId=app version=1.0.0
        assets: extension=jar
        filename: ./build/libs/SimpleHelloAPI-0.0.1-SNAPSHOT.jar